#image: ubuntu:latest
#image: microsoft/nanoserver

stages:
  - build
  - test

build_linux:
  stage: build
  image: ubuntu:latest
  script:
    - ls -l
    - echo "Build Linux" >> build.txt
    - cat build.txt
  artifacts:
    expire_in: 1 day
    paths:
      - build.txt

test_linux:
  stage: test
  image: ubuntu:latest
  dependencies:
    - build_linux
  script:
    - ls -l
    - cat build.txt
