#image: ubuntu:latest
#image: microsoft/nanoserver

stages:
  - build
  - test

build_linux:
  stage: build
  image: ubuntu:latest
  script:
    - ls -l
    - mkdir build
    - cd build
    - echo "Build Linux" >> build.txt
    - echo "Other content" >> content.txt
    - cat build.txt
    - cat content.txt
  artifacts:
    expire_in: 1 day
    paths:
      - build

test_linux:
  stage: test
  image: ubuntu:latest
  dependencies:
    - build_linux
  script:
    - ls -l
    - cat build/build.txt
    - cat build/content.txt
