#image: ubuntu:latest
#image: microsoft/nanoserver

stages:
  - build
  - test

build_linux:
  image: ubuntu:latest
  stage: build
  script:
    - ls -l
    - echo "Build Linux" >> build.txt
    - cat build.txt

test_linux:
  image: ubuntu:latest
  stage: test
  script:
    - ls -l
    - cat build.txt
