#image: microsoft/nanoserver

default:
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest

stages:
  - build
  - test

build_linux_debug:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_CONAN_TESTS=ON -DBUILD_DOCS=ON ..
    - make -j4
  artifacts:
    expire_in: 1 day
    paths:
      - build

test_linux_debug:
  stage: test
  dependencies:
    - build_linux_debug
  script:
    - cd build
    - ctest --output-on-failure .
