#image: microsoft/nanoserver

default:
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest

stages:
  - build
  - test
  - deploy

build_linux_debug:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_CONAN_TESTS=ON -DBUILD_DOCS=ON ..
    - make -j4
  artifacts:
    expire_in: 1 day # TODO check the default behaviour: delete after pipeline ???
    paths:
      - build

test_linux_debug:
  stage: test
  dependencies:
    - build_linux_debug
  script:
    - cd build
    - ctest --output-on-failure .


deploy_conan:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  before_script:
    - conan user -p $BINTRAY_API_KEY -r scandyna scandyna
  script:
    - conan create . scandyna/testing
    - conan upload MdtCMakeModules/*@scandyna/testing -r scandyna --all -c


pages:
  stage: deploy
  dependencies:
    - build_linux_debug
  script:
    - cd build
    - make documentation
    - cd ..
    - mv build/doc/html public
  artifacts:
    paths:
      - public
