
image: Visual Studio 2017

# NOTE: to build the PATH:
#  - Should not double quote them
#  - Never build the PATH on conditions using cmd (probably the default if not specified)
# Example:
#  if "%platform%"=="mingw" (set "PATH=%MINGW_PREFIX_PATH%\bin;%PATH%")
#  This allways gave a error like "\Microsoft was unexpected at this time"
#  Have try with double quotes, without, any combinations, simply never worked.
#  See also: http://www.blinnov.com/en/2010/06/04/microsoft-was-unexpected-at-this-time/
# The solution could be to use PowerShell

environment:
  matrix:
    # MinGW x86_64
    - name: mingw_x86_64
      platform: mingw
      CMAKE_GENERATOR: "MinGW Makefiles"
      MAKE_COMMAND: mingw32-make -j4
      QT_PREFIX_PATH: 'C:\Qt\5.13\mingw73_64'
      MINGW_PREFIX_PATH: 'C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64'
      extra_path_command: 'set PATH=%MINGW_PREFIX_PATH%\bin;%PATH%'
      before_build_extra_command: 'echo No before build extra command'
    # Visual Studio x86_64
    - name: msvc_x86_64
      platform: msvc
      CMAKE_GENERATOR: "NMake Makefiles"
      MAKE_COMMAND: nmake
      QT_PREFIX_PATH: 'C:\Qt\5.13.2\msvc2017_64'
      extra_path_command: 'set PATH=%PATH%'
      before_build_extra_command: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'

configuration:
  - Debug

before_build:
  - "%extra_path_command%"
  - "%before_build_extra_command%"
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # Thanks to: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%QT_PREFIX_PATH%\bin;%PATH%
  - echo %PATH%


# TODO: should not add QT_PREFIX_PATH\bin to PATH to check that mdt_target_libraries_to_library_env_path() works

build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE="%configuration%" -DQT_PREFIX_PATH="QT_PREFIX_PATH" -DBUILD_TESTS=ON -DBUILD_CONAN_TESTS=OFF -DBUILD_DOCS=OFF ..
  - "%MAKE_COMMAND%"

test_script:
  - ctest --output-on-failure .
