
image: Visual Studio 2017

# NOTE: to build the PATH:
#  - Should not double quote them
#  - Never build the PATH on conditions using cmd (probably the default if not specified)
# Example:
#  if "%platform%"=="mingw" (set "PATH=%MINGW_PREFIX_PATH%\bin;%PATH%")
#  This allways gave a error like "\Microsoft was unexpected at this time"
#  Have try with double quotes, without, any combinations, simply never worked.
#  See also: http://www.blinnov.com/en/2010/06/04/microsoft-was-unexpected-at-this-time/
# The solution could be to use PowerShell

environment:
  matrix:
    # MinGW x86_64
    - name: mingw_x86_64
      platform: mingw
      CMAKE_GENERATOR: "MinGW Makefiles"
      QT_PREFIX_PATH: 'C:\Qt\5.13\mingw73_64'
      MINGW_PREFIX_PATH: 'C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64'
      extra_path_command: 'set PATH=%MINGW_PREFIX_PATH%\bin;%PATH%'
    # Visual Studio x86_64
    - name: msvc_x86_64
      platform: msvc
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      QT_PREFIX_PATH: 'C:\Qt\5.13\msvc2017_64'
      extra_path_command: 'set PATH=%PATH%'

configuration:
  - Debug

before_build:
  - "%extra_path_command%"
  #- "%before_build_extra_command%"
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # Thanks to: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\Python38;%PATH%
  #- set PATH=%QT_PREFIX_PATH%\bin;C:\Python38;%PATH%
  - echo %PATH%
  - python --version
  - pip --version
  - pip install conan
  - conan user
  - conan --version


# TODO: should not add QT_PREFIX_PATH\bin to PATH to check that mdt_target_libraries_to_library_env_path() works

build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" "%CMAKE_GENERATOR_EXTRA_ARGUMENTS%" -DCMAKE_BUILD_TYPE="%configuration%" -DQT_PREFIX_PATH="QT_PREFIX_PATH" -DBUILD_TESTS=ON -DBUILD_CONAN_TESTS=ON -DBUILD_DOCS=OFF ..
  - cmake --build . --config "%configuration%"

test_script:
  - ctest --output-on-failure --build-config "%configuration%" -j4 .
